#!/usr/bin/env ruby

#
#    carray - Create a C array from a text.
#    Copyright (C) 2022  Jordan Niethe
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

modifiers = ARGV.shift
type = ARGV.shift
name = ARGV.shift

lines = ARGF.readlines
puts "// clang-format off"
puts "#{modifiers} #{type} #{name}[] = {"
lines[0..lines.length - 2].each do |l|
	print "\t"
	puts l.tr(" ", ",").sub(/(.*) /, '\1')
end

print "\t"
puts lines[lines.length - 1].tr(" ", ",").sub(/(.*),/, '\1')

puts "};"
puts "// clang-format on"